# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  project: '**/Core.Threading.csproj'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 2
  minor: 0
  patch: $[counter(variables['minor'], 0)] # will be reset when minor changes
  NugetVersion: $(major).$(minor).$(patch)

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use dotnet 6'
  inputs:
    version: '6.x'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    vstsFeed: 'LeaderAnalyticsFeed'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: $(project)


- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: $(project)
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'NugetVersion'

   

- task: NuGetCommand@2
  inputs:
    command: 'push'
    feedsToUse: 'select'
    vstsFeed: 'LeaderAnalyticsFeed'
    publishVstsFeed: 'LeaderAnalyticsFeed'